### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by karelbilek** [str4d/insight-api-zcash#1]
This is what I get when I try to install this (either through npm install or through bitcore-node install)

```
npm install str4d/insight-api-zcash
npm WARN engine insight-api-zcash@0.4.3: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache/add-named.js:240:24)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:84:10
npm ERR!     at RegClient.get_ (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.8.3-x86_64-linode76
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "str4d/insight-api-zcash"
npm ERR! cwd /home/karel/aaa
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! type called_on_non_object
^Bnpm WARN engine form-data@2.1.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/karel/aaa/npm-debug.log
npm ERR! not ok code 0
```

**Comment by karelbilek** [comment]
....ooh, it's clearer from the npm debug log. This is what I see

```
1454 silly lockFile 60f9a86f-ib-zcash-str4d-bitcore-lib-zcash bitcore-lib-zcash@str4d/bitcore-lib-zcash
1455 verbose lock bitcore-lib-zcash@str4d/bitcore-lib-zcash /home/karel/.npm/60f9a86f-ib-zcash-str4d-bitcore-lib-zcash.lock
1456 info addNameTag [ 'bitcore-lib-zcash', 'str4d/bitcore-lib-zcash' ]
1457 info preinstall body-parser@1.15.2
1458 verbose readDependencies using package.json deps
1459 verbose registry.get https://registry.npmjs.org/bitcore-lib-zcash not expired, no request
```

bitcore-lib-zcash is not in npm. (There is zcash-bitcore-lib but it's a fork of your project.)

**Comment by karelbilek** [comment]
Installing new npm fixed that. Sorry about that
