### ISSUE TITLE
Assertion Failed Error

### ISSUE THREAD

**Issue by garceri** [str4d/insight-api-zcash#5]
Tried using your ui/api packages following the install instructions, getting this error as soon as i try to browse a block
```
[2018-02-09T20:05:09.946Z] info: ::ffff:10.42.0.1 "GET /insight-api-zcash/sync" 200 117 1070.209 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.3 Waterfox/56.0.3"
[2018-02-09T20:05:09.951Z] error: uncaught exception: [Error: Assertion failed]
[2018-02-09T20:05:09.954Z] error: Error: Assertion failed
    at assert (/root/mynode/node_modules/bitcore-lib/node_modules/bn.js/lib/bn.js:9:11)
    at BN.divmod (/root/mynode/node_modules/bitcore-lib/node_modules/bn.js/lib/bn.js:1335:3)
    at BN.div (/root/mynode/node_modules/bitcore-lib/node_modules/bn.js/lib/bn.js:1382:15)
    at BlockHeader.getDifficulty (/root/mynode/node_modules/bitcore-lib/lib/block/blockheader.js:227:46)
    at BlockController.transformBlock (/root/mynode/node_modules/insight-api-zcash/lib/blocks.js:133:30)
    at /root/mynode/node_modules/insight-api-zcash/lib/blocks.js:76:32
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:676:51
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:726:13
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:264:21
[2018-02-09T20:05:09.955Z] info: Beginning shutdown
[2018-02-09T20:05:09.955Z] info: Stopping insight-ui-zcash
[2018-02-09T20:05:09.956Z] info: Stopping insight-api-zcash
[2018-02-09T20:05:09.957Z] info: Stopping web
[2018-02-09T20:05:09.958Z] info: Stopping bitcoind
```
``

**Comment by garceri** [comment]
Closing as this aligns with insight-ui
